name: dart_llm_workspace
repository: https://github.com/brynjen/dart-llm

command:
  bootstrap:
    # Run `dart pub get` in all packages
    runPubGetInParallel: true
  
  version:
    # Use conventional commits for versioning
    conventionalCommits: true
    # Update changelog automatically
    changelog: true
    # Update pubspec versions
    updatePubspecs: true
    # Create git tag
    gitTag: true
    # Do NOT auto-create GitHub releases (manual process)
    githubRelease: false
    # Prerelease support
    prerelease: true

scripts:
  # Get dependencies for all packages (just use melos bootstrap directly, no script needed)
  # Run tests for all packages
  test:
    exec: dart test
    description: Run tests for all packages
  
  # Analyze all packages
  analyze:
    exec: dart analyze
    description: Analyze code for all packages
  
  # Check formatting
  format:check:
    exec: dart format --set-exit-if-changed .
    description: Check code formatting for all packages
  
  # Clean build artifacts
  clean:
    exec: dart pub cache clean
    description: Clean build artifacts
  
  # Verify packages can be published (dry-run only, no actual publishing)
  publish:check:
    exec: dart pub publish --dry-run
    description: Verify all packages can be published (dry-run only, does not publish)
  
  # Run all checks (format, analyze, test)
  check:
    run: |
      melos format --set-exit-if-changed
      melos run analyze
      melos run test
    description: Run all code quality checks
