import 'package:llm_core/src/llm_message.dart';
import 'package:llm_core/src/tool/llm_invalid_tool_call.dart';
import 'package:llm_core/src/tool/llm_tool_call.dart';

/// Token usage reported by a model provider.
class LLMUsage {
  /// Creates token usage metadata.
  const LLMUsage({
    required this.promptTokens,
    required this.completionTokens,
    int? totalTokens,
    this.reasoningTokens,
  }) : totalTokens = totalTokens ?? promptTokens + completionTokens;

  /// Tokens consumed by the prompt/input.
  final int promptTokens;

  /// Tokens generated by the model.
  final int completionTokens;

  /// Total tokens for the request, when known.
  final int totalTokens;

  /// Tokens spent on thinking/reasoning, when the provider reports them.
  ///
  /// These are a subset of [completionTokens], not additional to it. Null
  /// when the provider does not break reasoning tokens out (Claude counts
  /// them inside output tokens; Ollama has no counter).
  final int? reasoningTokens;
}

/// Why a model response finished.
enum LLMFinishReason {
  /// The model stopped normally.
  stop('stop'),

  /// The model hit a length or token limit.
  length('length'),

  /// The model ended because it requested tool calls.
  toolCalls('tool_calls'),

  /// The model output was filtered.
  contentFilter('content_filter'),

  /// The provider's safety classifiers declined the request.
  ///
  /// Distinct from [contentFilter]: a refusal is returned as a **successful**
  /// HTTP response whose content is empty or partial, so without this value a
  /// declined request is indistinguishable from an empty answer. Check for it
  /// before treating a response as valid output.
  refusal('refusal'),

  /// Provider-specific or unknown finish reason.
  unknown('unknown');

  const LLMFinishReason(this.providerName);

  /// Common provider spelling for this finish reason.
  final String providerName;

  /// Converts a provider finish reason string into a typed value.
  ///
  /// Accepts the spellings used by Anthropic (`end_turn`, `stop_sequence`,
  /// `refusal`, …), OpenAI-compatible servers (`stop`, `length`, …) and Gemini
  /// (`STOP`, `MAX_TOKENS`, `RECITATION`, …).
  static LLMFinishReason fromProvider(String? value) {
    return switch (value) {
      'stop' || 'end_turn' || 'stop_sequence' || 'STOP' => LLMFinishReason.stop,
      'length' ||
      'max_tokens' ||
      'model_context_window_exceeded' ||
      'MAX_TOKENS' => LLMFinishReason.length,
      'tool_calls' || 'tool_use' || 'TOOL_CALLS' => LLMFinishReason.toolCalls,
      'content_filter' ||
      'SAFETY' ||
      'RECITATION' ||
      'PROHIBITED_CONTENT' ||
      'BLOCKLIST' ||
      'SPII' ||
      'IMAGE_SAFETY' => LLMFinishReason.contentFilter,
      'refusal' => LLMFinishReason.refusal,
      _ => LLMFinishReason.unknown,
    };
  }

  /// Whether a turn ending with this reason may be reclassified as a tool-call
  /// turn when the model produced complete tool calls.
  ///
  /// False for the reasons that contradict an executable call:
  /// * [length] — generation was cut off. Per the OpenAI specification the
  ///   turn *is* a truncation, whatever it carried, and the last call's
  ///   arguments may end mid-JSON. The calls are still surfaced, split by
  ///   whether their arguments decode (`LLMChunkMessage.toolCalls` and
  ///   `LLMChunkMessage.invalidToolCalls`), exactly as LangChain and the Vercel
  ///   AI SDK do; only the reason is never upgraded.
  /// * [contentFilter] and [refusal] — the provider declined the turn. These
  ///   are exactly the values a caller checks before treating a response as
  ///   valid output (see [refusal]); overwriting one would hide a safety
  ///   outcome behind a call the provider itself did not stand behind.
  ///
  /// LiteLLM draws the same line, for the same stated reason — "don't
  /// overwrite for other - potential error finish reasons".
  ///
  /// The switch is exhaustive on purpose: a new member of this enum will not
  /// compile until this decision has been made for it explicitly.
  bool get canBecomeToolCalls => switch (this) {
    stop || toolCalls || unknown => true,
    length || contentFilter || refusal => false,
  };

  /// Resolves the finish reason of a turn that carried complete tool calls.
  ///
  /// The OpenAI specification defines `finish_reason` as `tool_calls` "if the
  /// model called a tool" — a classification of what the turn did, not an
  /// opaque provider token. Providers violate this routinely:
  ///
  /// * vLLM reports `stop` for a named `tool_choice`, streaming and not;
  /// * Ollama's native `/api/chat` reports `stop` and delivers the calls on an
  ///   earlier, non-final frame;
  /// * OpenAI itself reports `stop` alongside a complete call intermittently;
  /// * Gemini has no tool-call status at all.
  ///
  /// One protocol-level rule covers all of them: a turn that ends while
  /// carrying complete, executable tool calls is a tool-call turn, whatever
  /// the provider spelled — unless its own reason contradicts the call being
  /// executable (see [canBecomeToolCalls]).
  ///
  /// [reported] is the provider's reason, already mapped through
  /// [fromProvider]; pass null when the provider gave none.
  /// [hasCompleteToolCalls] must be true only for **finished** calls. Fragments
  /// still arriving on `LLMChunkMessage.toolCallDeltas` never count: an
  /// argument fragment is part of a JSON document that only parses once every
  /// fragment has been concatenated.
  ///
  /// Only ever upgrades. A reported [toolCalls] is returned unchanged even when
  /// no calls were parsed, so this rule never contradicts a provider claiming a
  /// tool-call finish. A backend adapter may still correct a *specific, known*
  /// violation before calling this: vLLM reports `tool_calls` for a turn cut
  /// off by `max_tokens` mid-arguments (vllm-project/vllm#53269, closed not
  /// planned), which its adapter restores to [length].
  ///
  /// Call this **at a turn boundary only**. Mid-stream the accumulation is
  /// partial and the turn has not ended, so the question is not yet meaningful.
  static LLMFinishReason? resolve({
    required LLMFinishReason? reported,
    required bool hasCompleteToolCalls,
  }) {
    if (!hasCompleteToolCalls) return reported;
    if (reported == null) return LLMFinishReason.toolCalls;
    return reported.canBecomeToolCalls ? LLMFinishReason.toolCalls : reported;
  }
}

/// Represents a complete (non-streaming) response from an LLM.
class LLMResponse {
  LLMResponse({
    required this.model,
    required this.createdAt,
    required Object role,
    required this.content,
    required this.done,
    required this.doneReason,
    required this.promptEvalCount,
    required this.evalCount,
    required this.toolCalls,
    this.invalidToolCalls,
    this.thinking,
    LLMUsage? usage,
    LLMFinishReason? finishReason,
    this.providerMetadata = const {},
  }) : role = _normalizeRole(role),
       usage =
           usage ??
           LLMUsage(promptTokens: promptEvalCount, completionTokens: evalCount),
       finishReason = finishReason ?? LLMFinishReason.fromProvider(doneReason);

  /// The model that generated this response.
  final String model;

  /// When this response was created.
  final DateTime createdAt;

  /// The role of the responder.
  final LLMRole role;

  /// The role name for provider payloads and logs.
  String get roleName => role.name;

  /// The text content of the response.
  final String? content;

  /// Thinking/reasoning content, when the provider streams it separately.
  final String? thinking;

  /// Whether the response is complete.
  final bool done;

  /// The reason the response ended (e.g., "stop", "length", "tool_calls").
  final String doneReason;

  /// Number of tokens in the prompt.
  final int promptEvalCount;

  /// Number of tokens generated.
  final int evalCount;

  /// Tool calls requested by the model.
  final List<LLMToolCall>? toolCalls;

  /// Tool calls from the final turn whose arguments do not decode.
  ///
  /// Never executed. Check [finishReason]: [LLMFinishReason.length] means the
  /// turn was cut off mid-arguments. See [LLMInvalidToolCall].
  final List<LLMInvalidToolCall>? invalidToolCalls;

  /// First-class token usage metadata.
  final LLMUsage usage;

  /// First-class finish reason metadata.
  final LLMFinishReason finishReason;

  /// Provider-specific metadata that should be preserved but not standardized.
  final Map<String, dynamic> providerMetadata;

  static LLMRole _normalizeRole(Object role) {
    if (role is LLMRole) return role;
    if (role is String) {
      return LLMRole.values.firstWhere(
        (value) => value.name == role,
        orElse: () => LLMRole.assistant,
      );
    }
    throw ArgumentError.value(role, 'role', 'Expected LLMRole or role name');
  }
}
