import 'package:llm_core/src/llm_message.dart';
import 'package:llm_core/src/tool/llm_tool_call.dart';

/// Token usage reported by a model provider.
class LLMUsage {
  /// Creates token usage metadata.
  const LLMUsage({
    required this.promptTokens,
    required this.completionTokens,
    int? totalTokens,
    this.reasoningTokens,
  }) : totalTokens = totalTokens ?? promptTokens + completionTokens;

  /// Tokens consumed by the prompt/input.
  final int promptTokens;

  /// Tokens generated by the model.
  final int completionTokens;

  /// Total tokens for the request, when known.
  final int totalTokens;

  /// Tokens spent on thinking/reasoning, when the provider reports them.
  ///
  /// These are a subset of [completionTokens], not additional to it. Null
  /// when the provider does not break reasoning tokens out (Claude counts
  /// them inside output tokens; Ollama has no counter).
  final int? reasoningTokens;
}

/// Why a model response finished.
enum LLMFinishReason {
  /// The model stopped normally.
  stop('stop'),

  /// The model hit a length or token limit.
  length('length'),

  /// The model ended because it requested tool calls.
  toolCalls('tool_calls'),

  /// The model output was filtered.
  contentFilter('content_filter'),

  /// The provider's safety classifiers declined the request.
  ///
  /// Distinct from [contentFilter]: a refusal is returned as a **successful**
  /// HTTP response whose content is empty or partial, so without this value a
  /// declined request is indistinguishable from an empty answer. Check for it
  /// before treating a response as valid output.
  refusal('refusal'),

  /// Provider-specific or unknown finish reason.
  unknown('unknown');

  const LLMFinishReason(this.providerName);

  /// Common provider spelling for this finish reason.
  final String providerName;

  /// Converts a provider finish reason string into a typed value.
  ///
  /// Accepts the spellings used by Anthropic (`end_turn`, `stop_sequence`,
  /// `refusal`, …), OpenAI-compatible servers (`stop`, `length`, …) and Gemini
  /// (`STOP`, `MAX_TOKENS`, `RECITATION`, …).
  static LLMFinishReason fromProvider(String? value) {
    return switch (value) {
      'stop' || 'end_turn' || 'stop_sequence' || 'STOP' => LLMFinishReason.stop,
      'length' ||
      'max_tokens' ||
      'model_context_window_exceeded' ||
      'MAX_TOKENS' => LLMFinishReason.length,
      'tool_calls' || 'tool_use' || 'TOOL_CALLS' => LLMFinishReason.toolCalls,
      'content_filter' ||
      'SAFETY' ||
      'RECITATION' ||
      'PROHIBITED_CONTENT' ||
      'BLOCKLIST' ||
      'SPII' ||
      'IMAGE_SAFETY' => LLMFinishReason.contentFilter,
      'refusal' => LLMFinishReason.refusal,
      _ => LLMFinishReason.unknown,
    };
  }
}

/// Represents a complete (non-streaming) response from an LLM.
class LLMResponse {
  LLMResponse({
    required this.model,
    required this.createdAt,
    required Object role,
    required this.content,
    required this.done,
    required this.doneReason,
    required this.promptEvalCount,
    required this.evalCount,
    required this.toolCalls,
    this.thinking,
    LLMUsage? usage,
    LLMFinishReason? finishReason,
    this.providerMetadata = const {},
  }) : role = _normalizeRole(role),
       usage =
           usage ??
           LLMUsage(promptTokens: promptEvalCount, completionTokens: evalCount),
       finishReason = finishReason ?? LLMFinishReason.fromProvider(doneReason);

  /// The model that generated this response.
  final String model;

  /// When this response was created.
  final DateTime createdAt;

  /// The role of the responder.
  final LLMRole role;

  /// The role name for provider payloads and logs.
  String get roleName => role.name;

  /// The text content of the response.
  final String? content;

  /// Thinking/reasoning content, when the provider streams it separately.
  final String? thinking;

  /// Whether the response is complete.
  final bool done;

  /// The reason the response ended (e.g., "stop", "length", "tool_calls").
  final String doneReason;

  /// Number of tokens in the prompt.
  final int promptEvalCount;

  /// Number of tokens generated.
  final int evalCount;

  /// Tool calls requested by the model.
  final List<LLMToolCall>? toolCalls;

  /// First-class token usage metadata.
  final LLMUsage usage;

  /// First-class finish reason metadata.
  final LLMFinishReason finishReason;

  /// Provider-specific metadata that should be preserved but not standardized.
  final Map<String, dynamic> providerMetadata;

  static LLMRole _normalizeRole(Object role) {
    if (role is LLMRole) return role;
    if (role is String) {
      return LLMRole.values.firstWhere(
        (value) => value.name == role,
        orElse: () => LLMRole.assistant,
      );
    }
    throw ArgumentError.value(role, 'role', 'Expected LLMRole or role name');
  }
}
