include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat type errors strictly
    invalid_assignment: error
    invalid_null_aware_operator: error
    # Treat unused elements as warnings (not errors)
    unused_element: warning
    unused_field: warning
    unused_import: warning
    unused_local_variable: warning
  language:
    # Use strict mode but allow some flexibility for dynamic types from JSON
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Error rules
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - unawaited_futures
    # Style rules
    - always_use_package_imports
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_in_for_each
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_string_buffers
    - use_test_throws_matchers
    - void_checks

